Add possibility to upload image to users and services
iTechArt-RubyLab/organizer pull request #11
Opened 2023-05-04 15:23 UTC by ritamma

2023-05-04 16:49 UTC, fooooxmr requested changes

2023-05-04 16:49 UTC, fooooxmr commented on app/models/service.rb
> +    self.image_url = image&.url&.split('?')&.first
Use ActiveStorage method insted.

2023-05-04 16:49 UTC, fooooxmr commented on app/models/user.rb
> +    avatar_url = avatar&.url&.split('?')&.first
Use ActiveStorage method insted.

2023-05-04 16:49 UTC, fooooxmr commented on db/migrate/20230504140944_add_image_url_for_services.rb
> +    add_column :services, :image_url, :string
Not needed.

2023-05-06 09:27 UTC, ritamma commented on app/models/service.rb
> +    self.image_url = image&.url&.split('?')&.first
Done

2023-05-06 09:27 UTC, ritamma commented on app/models/user.rb
> +    avatar_url = avatar&.url&.split('?')&.first
Done

2023-05-06 09:27 UTC, ritamma commented on db/migrate/20230504140944_add_image_url_for_services.rb
> +    add_column :services, :image_url, :string
Done

2023-05-10 18:41 UTC, fooooxmr approved these changes

2023-05-10 18:41 UTC, merged