Add field name to users
iTechArt-RubyLab/organizer pull request #2
Opened 2023-04-06 16:11 UTC by ritamma

2023-04-06 17:25 UTC, fooooxmr requested changes

2023-04-06 17:25 UTC, fooooxmr commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
Check this line.

2023-04-06 17:25 UTC, fooooxmr commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.text_field :name, autofocus: true %>
Check what do autofocus.

2023-04-10 18:27 UTC, ritamma commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.text_field :name, autofocus: true %>
Done

2023-04-10 18:28 UTC, ritamma commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
We can use account_update, if we want to update users data, we have default routes for this action.

2023-04-11 15:06 UTC, fooooxmr approved these changes

2023-04-11 15:06 UTC, merged