Add mvc for booking
iTechArt-RubyLab/organizer pull request #7
Opened 2023-04-24 14:36 UTC by ritamma

2023-04-27 17:15 UTC, fooooxmr requested changes

2023-04-27 17:15 UTC, fooooxmr commented on app/controllers/bookings_controller.rb
> +    @booking.end_at -= 1
Move to before_validation callback.

2023-04-27 17:15 UTC, fooooxmr commented on app/controllers/bookings_controller.rb
> +      total_price_set
Move to callbacks.

2023-04-27 17:15 UTC, fooooxmr commented on app/models/booking.rb
> +    if total_d < 60 && service.name != 'Message chair'
Move logic to service.

2023-04-27 17:15 UTC, fooooxmr commented on app/models/booking.rb
> +    if service_id == 1 && Booking.with_service(1).reservations_overlap(end_at, start_at).count >= 5 ||
Do not use IDs inside validations.

2023-04-27 17:15 UTC, fooooxmr commented on app/models/booking.rb
> +    if service_id == 1 && Booking.with_service(1).reservations_overlap(end_at, start_at).count >= 5 ||
Add count of possible bookings to service.

2023-04-27 17:15 UTC, fooooxmr commented on app/models/service.rb
> +  has_many :bookings, dependent: :destroy
Do not destroy bookings.
Archive service, not destroy.

2023-04-27 17:15 UTC, fooooxmr commented on app/models/user.rb
> +  has_many :bookings, dependent: :destroy
Archive users not destroy.

2023-04-27 17:15 UTC, fooooxmr commented on db/migrate/20230419090150_create_bookings.rb
> +      t.integer :total_price
make total_price float

2023-04-27 17:15 UTC, fooooxmr commented on db/seeds.rb
> +                   id: 1,
remove ID from seeds.

2023-05-01 17:29 UTC, ritamma commented on app/controllers/bookings_controller.rb
> +    @booking.end_at -= 1
Done

2023-05-01 17:29 UTC, ritamma commented on app/models/booking.rb
> +    if total_d < 60 && service.name != 'Message chair'
Done

2023-05-01 17:29 UTC, ritamma commented on app/models/booking.rb
> +    if service_id == 1 && Booking.with_service(1).reservations_overlap(end_at, start_at).count >= 5 ||
Done

2023-05-01 17:30 UTC, ritamma commented on app/models/user.rb
> +  has_many :bookings, dependent: :destroy
Done

2023-05-01 17:30 UTC, ritamma commented on db/seeds.rb
> +                   id: 1,
Done

2023-05-02 09:55 UTC, fooooxmr approved these changes

2023-05-02 09:55 UTC, merged