Add field confirmable to users
iTechArt-RubyLab/organizer pull request #8
Opened 2023-04-26 10:31 UTC by ritamma

2023-04-27 17:04 UTC, fooooxmr requested changes

2023-04-27 17:04 UTC, fooooxmr commented on db/migrate/20230426094101_add_confirmable_to_devise.rb
> +    User.update_all confirmed_at: DateTime.now
Not a good practice.
Remove from migration.

2023-05-01 07:54 UTC, ritamma commented on db/migrate/20230426094101_add_confirmable_to_devise.rb
> +    User.update_all confirmed_at: DateTime.now
Done

2023-05-02 09:56 UTC, fooooxmr approved these changes

2023-05-02 10:05 UTC, merged